-- Positions table --
INSERT INTO position (nazwa) VALUES ('Head Doctor');
INSERT INTO position (nazwa) VALUES ('Pediatrician');
INSERT INTO position (nazwa) VALUES ('Surgeon');
INSERT INTO position (nazwa) VALUES ('Internist');
INSERT INTO position (nazwa) VALUES ('Radiologist');
INSERT INTO position (nazwa) VALUES ('Nurse');
INSERT INTO position (nazwa) VALUES ('Anesthesiologist');
INSERT INTO position (nazwa) VALUES ('Physiotherapist');
INSERT INTO position (nazwa) VALUES ('Lab Technician');
INSERT INTO position (nazwa) VALUES ('Clinical Psychologist');
INSERT INTO position (nazwa) VALUES ('Pharmacist');
INSERT INTO position (nazwa) VALUES ('Dietitian');
INSERT INTO position (nazwa) VALUES ('Receptionist');
INSERT INTO position (nazwa) VALUES ('Accountant');
INSERT INTO position (nazwa) VALUES ('System Administrator');
INSERT INTO position (nazwa) VALUES ('HR Manager');
INSERT INTO position (nazwa) VALUES ('Financial Controller');
INSERT INTO position (nazwa) VALUES ('Marketing Specialist');
INSERT INTO position (nazwa) VALUES ('Medical Secretary');
INSERT INTO position (nazwa) VALUES ('Porter');
INSERT INTO position (nazwa) VALUES ('Delivery Person');
INSERT INTO position (nazwa) VALUES ('Assistant Doctor');
INSERT INTO position (nazwa) VALUES ('Palliative Care Specialist');
INSERT INTO position (nazwa) VALUES ('Mental Health Care Specialist');
INSERT INTO position (nazwa) VALUES ('Sports Physiotherapist');
INSERT INTO position (nazwa) VALUES ('Occupational Therapist');
INSERT INTO position (nazwa) VALUES ('Social Worker');
INSERT INTO position (nazwa) VALUES ('Speech Therapist');
INSERT INTO position (nazwa) VALUES ('X-ray Technician');
INSERT INTO position (nazwa) VALUES ('Administrative Staff');
INSERT INTO position (nazwa) VALUES ('Public Health Advisor');
INSERT INTO position (nazwa) VALUES ('Midwife Nurse');
INSERT INTO position (nazwa) VALUES ('Speech Pathologist');
INSERT INTO position (nazwa) VALUES ('Pediatric Occupational Therapist');
INSERT INTO position (nazwa) VALUES ('Respiratory Therapist');
INSERT INTO position (nazwa) VALUES ('Medical Therapist');
INSERT INTO position (nazwa) VALUES ('Medical Technician');
INSERT INTO position (nazwa) VALUES ('Concierge');
INSERT INTO position (nazwa) VALUES ('Security Specialist');
INSERT INTO position (nazwa) VALUES ('Quality Manager');
INSERT INTO position (nazwa) VALUES ('Nurse Assistant');
INSERT INTO position (nazwa) VALUES ('Emergency Room Doctor');
INSERT INTO position (nazwa) VALUES ('Oncologist');
INSERT INTO position (nazwa) VALUES ('Cardiologist');
INSERT INTO position (nazwa) VALUES ('Neurologist');
INSERT INTO position (nazwa) VALUES ('Dermatologist');
INSERT INTO position (nazwa) VALUES ('Orthopedic Surgeon');
INSERT INTO position (nazwa) VALUES ('Urologist');
INSERT INTO position (nazwa) VALUES ('Ophthalmologist');
INSERT INTO position (nazwa) VALUES ('Gastroenterologist');
INSERT INTO position (nazwa) VALUES ('Endocrinologist');
INSERT INTO position (nazwa) VALUES ('Nephrologist');
INSERT INTO position (nazwa) VALUES ('Pulmonologist');
INSERT INTO position (nazwa) VALUES ('Infectious Disease Specialist');
INSERT INTO position (nazwa) VALUES ('Hematologist');
INSERT INTO position (nazwa) VALUES ('Allergist');
INSERT INTO position (nazwa) VALUES ('Anesthetist');
INSERT INTO position (nazwa) VALUES ('Otolaryngologist');
INSERT INTO position (nazwa) VALUES ('Pathologist');
INSERT INTO position (nazwa) VALUES ('Radiation Oncologist');
INSERT INTO position (nazwa) VALUES ('General Practitioner');

-- Employees table --

INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('john.doe@example.com', 'password123', 'John', 'Doe', '123456789', 1);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('jane.smith@example.com', 'password456', 'Jane', 'Smith', '987654321', 2);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('michael.johnson@example.com', 'password789', 'Michael', 'Johnson', '192837465', 3);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('robert.johnson@example.com', 'password123', 'Robert', 'Johnson', '555123456', 4);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('william.davis@example.com', 'password456', 'William', 'Davis', '555987654', 5);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('mary.wilson@example.com', 'password789', 'Mary', 'Wilson', '555192837', 6);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('linda.wilson@example.com', 'password123', 'Linda', 'Wilson', '555555123', 7);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('charles.thomas@example.com', 'password456', 'Charles', 'Thomas', '555555987', 8);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('patricia.jones@example.com', 'password789', 'Patricia', 'Jones', '555555192', 9);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('christopher.walker@example.com', 'password123', 'Christopher', 'Walker', '555555555', 10);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('elizabeth.hill@example.com', 'password456', 'Elizabeth', 'Hill', '555555666', 11);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('james.green@example.com', 'password789', 'James', 'Green', '555555777', 12);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('michelle.adams@example.com', 'password123', 'Michelle', 'Adams', '555555888', 13);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('daniel.baker@example.com', 'password456', 'Daniel', 'Baker', '555555999', 14);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('sarah.cook@example.com', 'password789', 'Sarah', 'Cook', '555555000', 15);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('jennifer.carter@example.com', 'password123', 'Jennifer', 'Carter', '555555111', 16);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('kevin.howard@example.com', 'password456', 'Kevin', 'Howard', '555555222', 17);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('laura.lopez@example.com', 'password789', 'Laura', 'Lopez', '555555333', 18);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('jason.lewis@example.com', 'password123', 'Jason', 'Lewis', '555555444', 19);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('lisa.ward@example.com', 'password456', 'Lisa', 'Ward', '555555555', 20);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('benjamin.lee@example.com', 'password789', 'Benjamin', 'Lee', '555555666', 21);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('natalie.walker@example.com', 'password123', 'Natalie', 'Walker', '555555777', 22);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('steven.allen@example.com', 'password456', 'Steven', 'Allen', '555555888', 23);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('victoria.lopez@example.com', 'password789', 'Victoria', 'Lopez', '555555999', 24);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('katherine.wright@example.com', 'password123', 'Katherine', 'Wright', '555555000', 25);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('gary.hill@example.com', 'password456', 'Gary', 'Hill', '555555111', 26);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('samantha.lopez@example.com', 'password789', 'Samantha', 'Lopez', '555555222', 27);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('alexander.young@example.com', 'password123', 'Alexander', 'Young', '555555333', 28);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('amanda.scott@example.com', 'password456', 'Amanda', 'Scott', '555555444', 29);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('ryan.mitchell@example.com', 'password789', 'Ryan', 'Mitchell', '555555555', 30);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('david.wood@example.com', 'password123', 'David', 'Wood', '555555666', 31);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('jessica.ward@example.com', 'password456', 'Jessica', 'Ward', '555555777', 32);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('thomas.king@example.com', 'password789', 'Thomas', 'King', '555555888', 33);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('megan.howard@example.com', 'password123', 'Megan', 'Howard', '555555999', 34);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('eric.cook@example.com', 'password456', 'Eric', 'Cook', '555555000', 35);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('olivia.bell@example.com', 'password789', 'Olivia', 'Bell', '555555111', 36);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('nathan.ward@example.com', 'password123', 'Nathan', 'Ward', '555555222', 37);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('sophia.baker@example.com', 'password456', 'Sophia', 'Baker', '555555333', 38);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('ethan.carter@example.com', 'password789', 'Ethan', 'Carter', '555555444', 39);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('isabella.allen@example.com', 'password123', 'Isabella', 'Allen', '555555555', 40);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('matthew.young@example.com', 'password456', 'Matthew', 'Young', '555555666', 41);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('emily.scott@example.com', 'password789', 'Emily', 'Scott', '555555777', 42);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('noah.thomas@example.com', 'password123', 'Noah', 'Thomas', '555555555', 40);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('olivia.jones@example.com', 'password456', 'Olivia', 'Jones', '555555666', 41);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('liam.wilson@example.com', 'password789', 'Liam', 'Wilson', '555555777', 42);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('emma.davis@example.com', 'password123', 'Emma', 'Davis', '555555888', 43);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('aiden.martin@example.com', 'password456', 'Aiden', 'Martin', '555555999', 44);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('ava.garcia@example.com', 'password789', 'Ava', 'Garcia', '555555000', 45);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('mia.martinez@example.com', 'password123', 'Mia', 'Martinez', '555555111', 46);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('mason.anderson@example.com', 'password456', 'Mason', 'Anderson', '555555222', 47);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('harper.lopez@example.com', 'password789', 'Harper', 'Lopez', '555555333', 48);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('amelia.lee@example.com', 'password123', 'Amelia', 'Lee', '555555444', 49);
INSERT INTO employee (email, password, imie, nazwisko, numer_tel, postion_id) VALUES ('logan.gonzalez@example.com', 'password456', 'Logan', 'Gonzalez', '555555555', 50);

-- Medicines table --

INSERT INTO medicine (nazwa) VALUES ('Aspirin');
INSERT INTO medicine (nazwa) VALUES ('Paracetamol');
INSERT INTO medicine (nazwa) VALUES ('Ibuprofen');
INSERT INTO medicine (nazwa) VALUES ('Amoxicillin');
INSERT INTO medicine (nazwa) VALUES ('Lisinopril');
INSERT INTO medicine (nazwa) VALUES ('Atorvastatin');
INSERT INTO medicine (nazwa) VALUES ('Metformin');
INSERT INTO medicine (nazwa) VALUES ('Simvastatin');
INSERT INTO medicine (nazwa) VALUES ('Amlodipine');
INSERT INTO medicine (nazwa) VALUES ('Metoprolol');
INSERT INTO medicine (nazwa) VALUES ('Omeprazole');
INSERT INTO medicine (nazwa) VALUES ('Losartan');
INSERT INTO medicine (nazwa) VALUES ('Gabapentin');
INSERT INTO medicine (nazwa) VALUES ('Hydrochlorothiazide');
INSERT INTO medicine (nazwa) VALUES ('Furosemide');
INSERT INTO medicine (nazwa) VALUES ('Albuterol');
INSERT INTO medicine (nazwa) VALUES ('Fluticasone');
INSERT INTO medicine (nazwa) VALUES ('Warfarin');
INSERT INTO medicine (nazwa) VALUES ('Ciprofloxacin');
INSERT INTO medicine (nazwa) VALUES ('Cetirizine');
INSERT INTO medicine (nazwa) VALUES ('Tramadol');
INSERT INTO medicine (nazwa) VALUES ('Prednisone');
INSERT INTO medicine (nazwa) VALUES ('Metronidazole');
INSERT INTO medicine (nazwa) VALUES ('Azithromycin');
INSERT INTO medicine (nazwa) VALUES ('Acetaminophen');
INSERT INTO medicine (nazwa) VALUES ('Fluoxetine');
INSERT INTO medicine (nazwa) VALUES ('Doxycycline');
INSERT INTO medicine (nazwa) VALUES ('Cephalexin');
INSERT INTO medicine (nazwa) VALUES ('Prednisolone');
INSERT INTO medicine (nazwa) VALUES ('Insulin');
INSERT INTO medicine (nazwa) VALUES ('Morphine');
INSERT INTO medicine (nazwa) VALUES ('Codeine');
INSERT INTO medicine (nazwa) VALUES ('Fentanyl');
INSERT INTO medicine (nazwa) VALUES ('Hydromorphone');
INSERT INTO medicine (nazwa) VALUES ('Methadone');
INSERT INTO medicine (nazwa) VALUES ('Buprenorphine');
INSERT INTO medicine (nazwa) VALUES ('Naloxone');
INSERT INTO medicine (nazwa) VALUES ('Methylphenidate');
INSERT INTO medicine (nazwa) VALUES ('Lisdexamfetamine');
INSERT INTO medicine (nazwa) VALUES ('Diazepam');
INSERT INTO medicine (nazwa) VALUES ('Venlafaxine');
INSERT INTO medicine (nazwa) VALUES ('Amitriptyline');
INSERT INTO medicine (nazwa) VALUES ('Lorazepam');
INSERT INTO medicine (nazwa) VALUES ('Clonazepam');
INSERT INTO medicine (nazwa) VALUES ('Citalopram');
INSERT INTO medicine (nazwa) VALUES ('Escitalopram');
INSERT INTO medicine (nazwa) VALUES ('Sertraline');
INSERT INTO medicine (nazwa) VALUES ('Trazodone');
INSERT INTO medicine (nazwa) VALUES ('Bupropion');
INSERT INTO medicine (nazwa) VALUES ('Duloxetine');
INSERT INTO medicine (nazwa) VALUES ('Mirtazapine');
INSERT INTO medicine (nazwa) VALUES ('Nortriptyline');
INSERT INTO medicine (nazwa) VALUES ('Olanzapine');
INSERT INTO medicine (nazwa) VALUES ('Quetiapine');
INSERT INTO medicine (nazwa) VALUES ('Risperidone');
INSERT INTO medicine (nazwa) VALUES ('Haloperidol');
INSERT INTO medicine (nazwa) VALUES ('Aripiprazole');
INSERT INTO medicine (nazwa) VALUES ('Paliperidone');
INSERT INTO medicine (nazwa) VALUES ('Ziprasidone');
INSERT INTO medicine (nazwa) VALUES ('Lurasidone');

-- Prescriptions table --

INSERT INTO prescription (nazwa) VALUES ('Prescription 1');
INSERT INTO prescription (nazwa) VALUES ('Prescription 2');
INSERT INTO prescription (nazwa) VALUES ('Prescription 3');
INSERT INTO prescription (nazwa) VALUES ('Prescription 4');
INSERT INTO prescription (nazwa) VALUES ('Prescription 5');
INSERT INTO prescription (nazwa) VALUES ('Prescription 6');
INSERT INTO prescription (nazwa) VALUES ('Prescription 7');
INSERT INTO prescription (nazwa) VALUES ('Prescription 8');
INSERT INTO prescription (nazwa) VALUES ('Prescription 9');
INSERT INTO prescription (nazwa) VALUES ('Prescription 10');
INSERT INTO prescription (nazwa) VALUES ('Prescription 11');
INSERT INTO prescription (nazwa) VALUES ('Prescription 12');
INSERT INTO prescription (nazwa) VALUES ('Prescription 13');
INSERT INTO prescription (nazwa) VALUES ('Prescription 14');
INSERT INTO prescription (nazwa) VALUES ('Prescription 15');
INSERT INTO prescription (nazwa) VALUES ('Prescription 16');
INSERT INTO prescription (nazwa) VALUES ('Prescription 17');
INSERT INTO prescription (nazwa) VALUES ('Prescription 18');
INSERT INTO prescription (nazwa) VALUES ('Prescription 19');
INSERT INTO prescription (nazwa) VALUES ('Prescription 20');
INSERT INTO prescription (nazwa) VALUES ('Prescription 21');
INSERT INTO prescription (nazwa) VALUES ('Prescription 22');
INSERT INTO prescription (nazwa) VALUES ('Prescription 23');
INSERT INTO prescription (nazwa) VALUES ('Prescription 24');
INSERT INTO prescription (nazwa) VALUES ('Prescription 25');
INSERT INTO prescription (nazwa) VALUES ('Prescription 26');
INSERT INTO prescription (nazwa) VALUES ('Prescription 27');
INSERT INTO prescription (nazwa) VALUES ('Prescription 28');
INSERT INTO prescription (nazwa) VALUES ('Prescription 29');
INSERT INTO prescription (nazwa) VALUES ('Prescription 30');
INSERT INTO prescription (nazwa) VALUES ('Prescription 31');
INSERT INTO prescription (nazwa) VALUES ('Prescription 32');
INSERT INTO prescription (nazwa) VALUES ('Prescription 33');
INSERT INTO prescription (nazwa) VALUES ('Prescription 34');
INSERT INTO prescription (nazwa) VALUES ('Prescription 35');
INSERT INTO prescription (nazwa) VALUES ('Prescription 36');
INSERT INTO prescription (nazwa) VALUES ('Prescription 37');
INSERT INTO prescription (nazwa) VALUES ('Prescription 38');
INSERT INTO prescription (nazwa) VALUES ('Prescription 39');
INSERT INTO prescription (nazwa) VALUES ('Prescription 40');
INSERT INTO prescription (nazwa) VALUES ('Prescription 41');
INSERT INTO prescription (nazwa) VALUES ('Prescription 42');
INSERT INTO prescription (nazwa) VALUES ('Prescription 43');
INSERT INTO prescription (nazwa) VALUES ('Prescription 44');
INSERT INTO prescription (nazwa) VALUES ('Prescription 45');
INSERT INTO prescription (nazwa) VALUES ('Prescription 46');
INSERT INTO prescription (nazwa) VALUES ('Prescription 47');
INSERT INTO prescription (nazwa) VALUES ('Prescription 48');
INSERT INTO prescription (nazwa) VALUES ('Prescription 49');
INSERT INTO prescription (nazwa) VALUES ('Prescription 50');
INSERT INTO prescription (nazwa) VALUES ('Prescription 51');
INSERT INTO prescription (nazwa) VALUES ('Prescription 52');
INSERT INTO prescription (nazwa) VALUES ('Prescription 53');
INSERT INTO prescription (nazwa) VALUES ('Prescription 54');
INSERT INTO prescription (nazwa) VALUES ('Prescription 55');
INSERT INTO prescription (nazwa) VALUES ('Prescription 56');
INSERT INTO prescription (nazwa) VALUES ('Prescription 57');
INSERT INTO prescription (nazwa) VALUES ('Prescription 58');
INSERT INTO prescription (nazwa) VALUES ('Prescription 59');
INSERT INTO prescription (nazwa) VALUES ('Prescription 60');
INSERT INTO prescription (nazwa) VALUES ('Prescription 61');
INSERT INTO prescription (nazwa) VALUES ('Prescription 62');
INSERT INTO prescription (nazwa) VALUES ('Prescription 63');
INSERT INTO prescription (nazwa) VALUES ('Prescription 64');
INSERT INTO prescription (nazwa) VALUES ('Prescription 65');
INSERT INTO prescription (nazwa) VALUES ('Prescription 66');
INSERT INTO prescription (nazwa) VALUES ('Prescription 67');
INSERT INTO prescription (nazwa) VALUES ('Prescription 68');
INSERT INTO prescription (nazwa) VALUES ('Prescription 69');
INSERT INTO prescription (nazwa) VALUES ('Prescription 70');

-- medicines_prescriptions table --

INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (1, 1);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (2, 1);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (3, 2);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (4, 2);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (5, 3);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (6, 3);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (7, 4);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (8, 4);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (9, 5);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (10, 5);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (11, 6);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (12, 6);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (13, 7);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (14, 7);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (15, 8);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (16, 8);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (17, 9);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (18, 9);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (19, 10);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (20, 10);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (1, 11);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (2, 11);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (3, 11);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (4, 11);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (5, 11);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (6, 12);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (7, 12);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (8, 12);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (9, 12);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (10, 12);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (11, 13);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (12, 13);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (13, 13);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (14, 13);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (15, 13);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (16, 14);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (17, 14);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (18, 14);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (19, 14);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (20, 14);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (5, 15);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (10, 15);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (15, 15);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (20, 15);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (6, 16);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (11, 16);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (16, 16);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (7, 17);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (12, 17);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (17, 17);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (1, 18);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (2, 18);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (3, 18);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (4, 18);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (5, 18);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (6, 19);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (7, 19);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (8, 19);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (9, 20);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (10, 21);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (11, 21);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (12, 21);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (13, 21);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (14, 22);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (15, 22);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (16, 23);
INSERT INTO prescription_medicine (medicine_id, prescription_id) VALUES (17, 24);

-- adress table --

INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Warszawa', 'Mazowieckie', 'Polska', 'Aleje Jerozolimskie', '1', '2', '00-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Kraków', 'Małopolskie', 'Polska', 'Rynek Główny', '3', '4', '30-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Łódź', 'Łódzkie', 'Polska', 'Piotrkowska', '5', '6', '90-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Wrocław', 'Dolnośląskie', 'Polska', 'Rynek', '7', '8', '50-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Poznań', 'Wielkopolskie', 'Polska', 'Stary Rynek', '9', '10', '60-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Gdańsk', 'Pomorskie', 'Polska', 'Długi Targ', '11', '12', '80-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Szczecin', 'Zachodniopomorskie', 'Polska', 'Wały Chrobrego', '13', '14', '70-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Bydgoszcz', 'Kujawsko-Pomorskie', 'Polska', 'Stary Rynek', '15', '16', '85-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Lublin', 'Lubelskie', 'Polska', 'Plac Litewski', '17', '18', '20-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Katowice', 'Śląskie', 'Polska', 'Rynek', '19', '20', '40-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Gdynia', 'Pomorskie', 'Polska', 'Bulwar Nadmorski', '21', '22', '81-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Częstochowa', 'Śląskie', 'Polska', 'Aleja Najświętszej Maryi Panny', '23', '24', '42-200');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Radom', 'Mazowieckie', 'Polska', 'Plac Konstytucji', '25', '26', '26-600');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Sosnowiec', 'Śląskie', 'Polska', 'Plac Kościuszki', '27', '28', '41-200');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Toruń', 'Kujawsko-Pomorskie', 'Polska', 'Stary Rynek', '29', '30', '87-100');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Kielce', 'Świętokrzyskie', 'Polska', 'Plac Artystów', '31', '32', '25-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Gliwice', 'Śląskie', 'Polska', 'Plac Rzeźnika', '33', '34', '44-100');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Zabrze', 'Śląskie', 'Polska', 'Plac Teatralny', '35', '36', '41-800');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Olsztyn', 'Warmińsko-Mazurskie', 'Polska', 'Aleja Marszałka Józefa Piłsudskiego', '37', '38', '10-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Bielsko-Biała', 'Śląskie', 'Polska', 'Plac Chrobrego', '39', '40', '43-300');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Rzeszów', 'Podkarpackie', 'Polska', 'Plac Wolności', '41', '42', '35-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Ruda Śląska', 'Śląskie', 'Polska', 'Aleja Korfantego', '43', '44', '41-700');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Tychy', 'Śląskie', 'Polska', 'Plac Sikorskiego', '45', '46', '43-100');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Opole', 'Opolskie', 'Polska', 'Plac Wolności', '47', '48', '45-001');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Gorzów Wielkopolski', 'Lubuskie', 'Polska', 'Plac Klasztorny', '49', '50', '66-400');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Elbląg', 'Warmińsko-Mazurskie', 'Polska', 'Plac Słowiański', '51', '52', '82-300');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Płock', 'Mazowieckie', 'Polska', 'Aleja Jana Pawła II', '53', '54', '09-400');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Wałbrzych', 'Dolnośląskie', 'Polska', 'Plac Księcia Bolesława I', '55', '56', '58-300');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Tarnów', 'Małopolskie', 'Polska', 'Rynek', '57', '58', '33-100');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Chorzów', 'Śląskie', 'Polska', 'Plac Wolności', '59', '60', '41-500');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Słupsk', 'Pomorskie', 'Polska', 'Plac Zwycięstwa', '61', '62', '76-200');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Jaworzno', 'Śląskie', 'Polska', 'Plac 3 Maja', '63', '64', '43-600');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Jastrzębie-Zdrój', 'Śląskie', 'Polska', 'Plac Ratuszowy', '65', '66', '44-335');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Mielec', 'Podkarpackie', 'Polska', 'Plac Niepodległości', '67', '68', '39-300');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Nowy Sącz', 'Małopolskie', 'Polska', 'Plac Świętego Piotra', '69', '70', '33-300');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Jelenia Góra', 'Dolnośląskie', 'Polska', 'Plac Ratuszowy', '71', '72', '58-500');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Ostrów Wielkopolski', 'Wielkopolskie', 'Polska', 'Plac Wolności', '73', '74', '63-400');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Stargard', 'Zachodniopomorskie', 'Polska', 'Plac Katedralny', '75', '76', '73-110');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Piotrków Trybunalski', 'Łódzkie', 'Polska', 'Plac Kościuszki', '77', '78', '97-300');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Lębork', 'Pomorskie', 'Polska', 'Plac Wolności', '79', '80', '84-300');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Gniezno', 'Wielkopolskie', 'Polska', 'Plac Świętego Wojciecha', '81', '82', '62-200');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Suwałki', 'Podlaskie', 'Polska', 'Plac Kościuszki', '83', '84', '16-400');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Goleniów', 'Zachodniopomorskie', 'Polska', 'Plac Wolności', '85', '86', '72-100');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Ostróda', 'Warmińsko-Mazurskie', 'Polska', 'Plac Jana Pawła II', '87', '88', '14-100');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Siedlce', 'Mazowieckie', 'Polska', 'Plac Piłsudskiego', '89', '90', '08-100');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Mysłowice', 'Śląskie', 'Polska', 'Plac Wolności', '91', '92', '41-400');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Bolesławiec', 'Dolnośląskie', 'Polska', 'Plac Konstytucji 3 Maja', '93', '94', '59-700');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Piła', 'Wielkopolskie', 'Polska', 'Plac Staszica', '95', '96', '64-920');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Włocławek', 'Kujawsko-Pomorskie', 'Polska', 'Plac Wolności', '97', '98', '87-800');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Tarnowskie Góry', 'Śląskie', 'Polska', 'Plac Piastów', '99', '100', '42-600');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Przemyśl', 'Podkarpackie', 'Polska', 'Plac Mickiewicza', '101', '102', '37-700');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Białogard', 'Zachodniopomorskie', 'Polska', 'Plac Wolności', '103', '104', '78-200');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Puławy', 'Lubelskie', 'Polska', 'Plac Kościuszki', '105', '106', '24-100');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Kędzierzyn-Koźle', 'Opolskie', 'Polska', 'Plac Wolności', '107', '108', '47-220');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Mikołów', 'Śląskie', 'Polska', 'Plac Jana Pawła II', '109', '110', '43-190');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Świdnica', 'Dolnośląskie', 'Polska', 'Plac Grunwaldzki', '111', '112', '58-100');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Ełk', 'Warmińsko-Mazurskie', 'Polska', 'Plac Wolności', '113', '114', '19-300');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Pruszków', 'Mazowieckie', 'Polska', 'Plac Kościuszki', '115', '116', '05-800');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Lubin', 'Dolnośląskie', 'Polska', 'Plac Wolności', '117', '118', '59-300');
INSERT INTO adress (miasto, wojewodztwo, kraj, ulica, numer_domu, numer_mieszkania, kod_pocztowy) VALUES ('Krosno', 'Podkarpackie', 'Polska', 'Plac Wolności', '119', '120', '38-400');

-- permissions table --

INSERT INTO permissions (nazwa) VALUES ('create_user');
INSERT INTO permissions (nazwa) VALUES ('delete_user');
INSERT INTO permissions (nazwa) VALUES ('update_user');
INSERT INTO permissions (nazwa) VALUES ('view_user');
INSERT INTO permissions (nazwa) VALUES ('create_role');
INSERT INTO permissions (nazwa) VALUES ('delete_role');
INSERT INTO permissions (nazwa) VALUES ('update_role');
INSERT INTO permissions (nazwa) VALUES ('view_role');
INSERT INTO permissions (nazwa) VALUES ('create_permission');
INSERT INTO permissions (nazwa) VALUES ('delete_permission');
INSERT INTO permissions (nazwa) VALUES ('update_permission');
INSERT INTO permissions (nazwa) VALUES ('view_permission');
INSERT INTO permissions (nazwa) VALUES ('assign_role');
INSERT INTO permissions (nazwa) VALUES ('revoke_role');
INSERT INTO permissions (nazwa) VALUES ('assign_permission');
INSERT INTO permissions (nazwa) VALUES ('revoke_permission');
INSERT INTO permissions (nazwa) VALUES ('create_patient_record');
INSERT INTO permissions (nazwa) VALUES ('delete_patient_record');
INSERT INTO permissions (nazwa) VALUES ('update_patient_record');
INSERT INTO permissions (nazwa) VALUES ('view_patient_record');
INSERT INTO permissions (nazwa) VALUES ('create_doctor_record');
INSERT INTO permissions (nazwa) VALUES ('delete_doctor_record');
INSERT INTO permissions (nazwa) VALUES ('update_doctor_record');
INSERT INTO permissions (nazwa) VALUES ('view_doctor_record');
INSERT INTO permissions (nazwa) VALUES ('create_nurse_record');
INSERT INTO permissions (nazwa) VALUES ('delete_nurse_record');
INSERT INTO permissions (nazwa) VALUES ('update_nurse_record');
INSERT INTO permissions (nazwa) VALUES ('view_nurse_record');
INSERT INTO permissions (nazwa) VALUES ('create_admin_record');
INSERT INTO permissions (nazwa) VALUES ('delete_admin_record');
INSERT INTO permissions (nazwa) VALUES ('update_admin_record');
INSERT INTO permissions (nazwa) VALUES ('view_admin_record');
INSERT INTO permissions (nazwa) VALUES ('create_appointment');
INSERT INTO permissions (nazwa) VALUES ('delete_appointment');
INSERT INTO permissions (nazwa) VALUES ('update_appointment');
INSERT INTO permissions (nazwa) VALUES ('view_appointment');
INSERT INTO permissions (nazwa) VALUES ('create_prescription');
INSERT INTO permissions (nazwa) VALUES ('delete_prescription');
INSERT INTO permissions (nazwa) VALUES ('update_prescription');
INSERT INTO permissions (nazwa) VALUES ('view_prescription');
INSERT INTO permissions (nazwa) VALUES ('create_medical_test');
INSERT INTO permissions (nazwa) VALUES ('delete_medical_test');
INSERT INTO permissions (nazwa) VALUES ('update_medical_test');
INSERT INTO permissions (nazwa) VALUES ('view_medical_test');
INSERT INTO permissions (nazwa) VALUES ('create_billing');
INSERT INTO permissions (nazwa) VALUES ('delete_billing');
INSERT INTO permissions (nazwa) VALUES ('update_billing');
INSERT INTO permissions (nazwa) VALUES ('view_billing');
INSERT INTO permissions (nazwa) VALUES ('create_department');
INSERT INTO permissions (nazwa) VALUES ('delete_department');
INSERT INTO permissions (nazwa) VALUES ('update_department');
INSERT INTO permissions (nazwa) VALUES ('view_department');
INSERT INTO permissions (nazwa) VALUES ('create_shift');
INSERT INTO permissions (nazwa) VALUES ('delete_shift');
INSERT INTO permissions (nazwa) VALUES ('update_shift');
INSERT INTO permissions (nazwa) VALUES ('view_shift');
INSERT INTO permissions (nazwa) VALUES ('create_schedule');
INSERT INTO permissions (nazwa) VALUES ('delete_schedule');
INSERT INTO permissions (nazwa) VALUES ('update_schedule');
INSERT INTO permissions (nazwa) VALUES ('view_schedule');
INSERT INTO permissions (nazwa) VALUES ('create_inventory');
INSERT INTO permissions (nazwa) VALUES ('delete_inventory');
INSERT INTO permissions (nazwa) VALUES ('update_inventory');
INSERT INTO permissions (nazwa) VALUES ('view_inventory');
INSERT INTO permissions (nazwa) VALUES ('create_bed');
INSERT INTO permissions (nazwa) VALUES ('delete_bed');
INSERT INTO permissions (nazwa) VALUES ('update_bed');
INSERT INTO permissions (nazwa) VALUES ('view_bed');
INSERT INTO permissions (nazwa) VALUES ('create_waiver');
INSERT INTO permissions (nazwa) VALUES ('delete_waiver');
INSERT INTO permissions (nazwa) VALUES ('update_waiver');
INSERT INTO permissions (nazwa) VALUES ('view_waiver');
INSERT INTO permissions (nazwa) VALUES ('create_surgery');
INSERT INTO permissions (nazwa) VALUES ('delete_surgery');
INSERT INTO permissions (nazwa) VALUES ('update_surgery');
INSERT INTO permissions (nazwa) VALUES ('view_surgery');
INSERT INTO permissions (nazwa) VALUES ('create_patient_payment');
INSERT INTO permissions (nazwa) VALUES ('delete_patient_payment');
INSERT INTO permissions (nazwa) VALUES ('update_patient_payment');
INSERT INTO permissions (nazwa) VALUES ('view_patient_payment');
INSERT INTO permissions (nazwa) VALUES ('create_medical_equipment');
INSERT INTO permissions (nazwa) VALUES ('delete_medical_equipment');
INSERT INTO permissions (nazwa) VALUES ('update_medical_equipment');
INSERT INTO permissions (nazwa) VALUES ('view_medical_equipment');
INSERT INTO permissions (nazwa) VALUES ('create_patient_admission');
INSERT INTO permissions (nazwa) VALUES ('delete_patient_admission');
INSERT INTO permissions (nazwa) VALUES ('update_patient_admission');
INSERT INTO permissions (nazwa) VALUES ('view_patient_admission');
INSERT INTO permissions (nazwa) VALUES ('create_patient_discharge');
INSERT INTO permissions (nazwa) VALUES ('delete_patient_discharge');
INSERT INTO permissions (nazwa) VALUES ('update_patient_discharge');
INSERT INTO permissions (nazwa) VALUES ('view_patient_discharge');
INSERT INTO permissions (nazwa) VALUES ('create_doctor_note');
INSERT INTO permissions (nazwa) VALUES ('delete_doctor_note');
INSERT INTO permissions (nazwa) VALUES ('update_doctor_note');
INSERT INTO permissions (nazwa) VALUES ('view_doctor_note');
INSERT INTO permissions (nazwa) VALUES ('create_nurse_note');
INSERT INTO permissions (nazwa) VALUES ('delete_nurse_note');
INSERT INTO permissions (nazwa) VALUES ('update_nurse_note');
INSERT INTO permissions (nazwa) VALUES ('view_nurse_note');
INSERT INTO permissions (nazwa) VALUES ('create_admin_note');
INSERT INTO permissions (nazwa) VALUES ('delete_admin_note');
INSERT INTO permissions (nazwa) VALUES ('update_admin_note');
INSERT INTO permissions (nazwa) VALUES ('view_admin_note');
INSERT INTO permissions (nazwa) VALUES ('create_medical_report');
INSERT INTO permissions (nazwa) VALUES ('delete_medical_report');
INSERT INTO permissions (nazwa) VALUES ('update_medical_report');
INSERT INTO permissions (nazwa) VALUES ('view_medical_report');
INSERT INTO permissions (nazwa) VALUES ('create_medical_certificate');
INSERT INTO permissions (nazwa) VALUES ('delete_medical_certificate');
INSERT INTO permissions (nazwa) VALUES ('update_medical_certificate');
INSERT INTO permissions (nazwa) VALUES ('view_medical_certificate');
INSERT INTO permissions (nazwa) VALUES ('create_medical_history');
INSERT INTO permissions (nazwa) VALUES ('delete_medical_history');
INSERT INTO permissions (nazwa) VALUES ('update_medical_history');
INSERT INTO permissions (nazwa) VALUES ('view_medical_history');
INSERT INTO permissions (nazwa) VALUES ('create_medical_billing');
INSERT INTO permissions (nazwa) VALUES ('delete_medical_billing');
INSERT INTO permissions (nazwa) VALUES ('update_medical_billing');
INSERT INTO permissions (nazwa) VALUES ('view_medical_billing');
INSERT INTO permissions (nazwa) VALUES ('create_medical_results');
INSERT INTO permissions (nazwa) VALUES ('delete_medical_results');
INSERT INTO permissions (nazwa) VALUES ('update_medical_results');
INSERT INTO permissions (nazwa) VALUES ('view_medical_results');
INSERT INTO permissions (nazwa) VALUES ('create_medical_image');
INSERT INTO permissions (nazwa) VALUES ('delete_medical_image');
INSERT INTO permissions (nazwa) VALUES ('update_medical_image');
INSERT INTO permissions (nazwa) VALUES ('view_medical_image');
INSERT INTO permissions (nazwa) VALUES ('create_patient_profile');
INSERT INTO permissions (nazwa) VALUES ('delete_patient_profile');
INSERT INTO permissions (nazwa) VALUES ('update_patient_profile');
INSERT INTO permissions (nazwa) VALUES ('view_patient_profile');

-- hospital_referral table --

INSERT INTO hospital_referral (opis) VALUES ('Referral for Cardiology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Orthopedic Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Neurology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Gastroenterology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Dermatology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Ophthalmology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Oncology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Urology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pulmonology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Endocrinology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Psychiatry Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Obstetrics Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Gynecology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Radiology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Nephrology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Hematology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Rheumatology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Allergy and Immunology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Otolaryngology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Vascular Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Plastic Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for General Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Maxillofacial Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Anesthesiology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Physical Therapy Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Occupational Therapy Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Speech Therapy Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Respiratory Therapy Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Nutrition Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Podiatry Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Infectious Disease Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pain Management Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Cardiac Rehabilitation Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Diabetes Education Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Genetic Counseling Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Palliative Care Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Sleep Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Addiction Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Geriatric Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Sports Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Wound Care Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Trauma Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Bariatric Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Behavioral Health Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Neurosurgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Geriatric Psychiatry Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Cardiothoracic Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Maternal-Fetal Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Neonatology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pain Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Nuclear Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Adolescent Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Developmental-Behavioral Pediatrics Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Forensic Psychiatry Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Sleep Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Vascular Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Interventional Radiology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Anesthesiology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Cardiology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Emergency Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Gastroenterology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Hematology-Oncology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Nephrology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Neurology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Ophthalmology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Orthopedics Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Pulmonology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Rheumatology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Urology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Genetics Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Infectious Diseases Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Endocrinology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Dermatology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Allergy and Immunology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Behavioral and Developmental Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Sports Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Radiology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Gynecology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Otolaryngology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Plastic Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Anesthesia Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Rehabilitation Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Dentistry Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Infectious Disease Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Cardiac Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Oncology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Nephrology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Neurosurgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Gastroenterology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Endocrinology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Pulmonology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Allergy and Immunology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Rheumatology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Dermatology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Emergency Medicine Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Radiology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Surgery Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Ophthalmology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Orthopedics Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Psychiatry Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Urology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Genetics Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Infectious Diseases Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Hematology-Oncology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Neurology Consultation');
INSERT INTO hospital_referral (opis) VALUES ('Referral for Pediatric Critical Care Consultation');

-- permissions_employee table --


-- patient table --


-- permissions_patient table --


-- department table --


-- appointment table --























