# Generated by Django 4.2.6 on 2023-12-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylifeclinic_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'ranking',
                'managed': False,
            },
        ),
    ]
